/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.rezervatsiyagithub.testing;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Emircan & Çağrı
 */
public class musteri1 extends javax.swing.JFrame {

    /**
     * Creates new form musteri1
     */
    public musteri1() {
        initComponents();
    }
    private payment paymentInstance;
    
    public musteri1(payment paymentInstance) {
        initComponents();
        this.paymentInstance = paymentInstance;
    }
    public void setPaymentInstance(payment paymentInstance) {
        this.paymentInstance = paymentInstance;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Aramabutonpanel1 = new javax.swing.JPanel();
        aramabutonu1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Chosewhere1 = new javax.swing.JLabel();
        Aramabutonpanelke = new javax.swing.JPanel();
        aramabutonu = new javax.swing.JLabel();
        neredennereye = new javax.swing.JPanel();
        From = new javax.swing.JLabel();
        To = new javax.swing.JLabel();
        Departure = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        To_Dropbox = new javax.swing.JComboBox<>();
        From_Dropbox = new javax.swing.JComboBox<>();
        To_Dropbox1 = new javax.swing.JComboBox<>();
        Chosewhere = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Firma F");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 87, -1));

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Uçak 1");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 87, 30));

        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("1000");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 87, 30));

        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("2");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 87, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Check In");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 79, 153, 39));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton1.setText("Check");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 130, -1));

        Aramabutonpanel1.setBackground(new java.awt.Color(246, 195, 63));
        Aramabutonpanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        aramabutonu1.setBackground(new java.awt.Color(0, 0, 0));
        aramabutonu1.setForeground(new java.awt.Color(246, 195, 63));
        aramabutonu1.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Belgeler\\NetBeansProjects\\rezervatsiyagithub\\src\\main\\java\\com\\mycompany\\rezervatsiyagithub\\testing\\Rezervatsiyaicon.png")); // NOI18N
        aramabutonu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aramabutonu1MouseClicked(evt);
            }
        });
        Aramabutonpanel1.add(aramabutonu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 100, 80));

        jPanel2.add(Aramabutonpanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 240, 86));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Belgeler\\NetBeansProjects\\rezervatsiyagithub\\src\\main\\java\\com\\mycompany\\rezervatsiyagithub\\testing\\checkin3.png")); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 420));

        Chosewhere1.setBackground(new java.awt.Color(9, 77, 255));
        Chosewhere1.setOpaque(true);
        jPanel2.add(Chosewhere1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 420));

        Aramabutonpanelke.setBackground(new java.awt.Color(246, 195, 63));
        Aramabutonpanelke.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        aramabutonu.setBackground(new java.awt.Color(0, 0, 0));
        aramabutonu.setForeground(new java.awt.Color(246, 195, 63));
        aramabutonu.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Belgeler\\NetBeansProjects\\rezervatsiyagithub\\src\\main\\java\\com\\mycompany\\rezervatsiyagithub\\testing\\Rezervatsiyaicon.png")); // NOI18N
        aramabutonu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aramabutonuMouseClicked(evt);
            }
        });
        Aramabutonpanelke.add(aramabutonu, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 100, 80));

        neredennereye.setBackground(new java.awt.Color(255, 187, 9));
        neredennereye.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        From.setBackground(new java.awt.Color(255, 187, 9));
        From.setFont(new java.awt.Font("Montserrat Black", 0, 18)); // NOI18N
        From.setForeground(new java.awt.Color(255, 255, 255));
        From.setText("Nereden");
        From.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "From", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 14), new java.awt.Color(9, 77, 255))); // NOI18N
        From.setOpaque(true);
        neredennereye.add(From, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 100, 40));

        To.setBackground(new java.awt.Color(255, 187, 9));
        To.setFont(new java.awt.Font("Montserrat Black", 0, 18)); // NOI18N
        To.setForeground(new java.awt.Color(255, 255, 255));
        To.setText("Nereye");
        To.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "To", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 14), new java.awt.Color(9, 77, 255))); // NOI18N
        To.setOpaque(true);
        neredennereye.add(To, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 100, 40));

        Departure.setBackground(new java.awt.Color(255, 187, 9));
        Departure.setFont(new java.awt.Font("Montserrat Black", 0, 18)); // NOI18N
        Departure.setForeground(new java.awt.Color(255, 255, 255));
        Departure.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Departure.setText("Kalkış");
        Departure.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Departure", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 13), new java.awt.Color(9, 77, 255))); // NOI18N
        Departure.setOpaque(true);
        neredennereye.add(Departure, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 100, 40));

        jDateChooser1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        neredennereye.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 352, 180, -1));

        To_Dropbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "04.12.2023", "05.12.2023", "06.12.2023", "07.12.2023", "08.12.2023", "09.12.2023", "10.12.2023"}));
        To_Dropbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                To_DropboxActionPerformed(evt);
            }
        });
        neredennereye.add(To_Dropbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 180, 20));

        From_Dropbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "İstanbul", "Kocaeli", "Ankara", "Eskişehir", "Konya"}));
        neredennereye.add(From_Dropbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 180, -1));

        To_Dropbox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "İstanbul", "Kocaeli", "Ankara", "Eskişehir", "Konya"}));
        neredennereye.add(To_Dropbox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 180, -1));

        Chosewhere.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\OneDrive\\Belgeler\\NetBeansProjects\\rezervatsiyagithub\\src\\main\\java\\com\\mycompany\\rezervatsiyagithub\\testing\\Musterifoto01_transparent.png")); // NOI18N
        neredennereye.add(Chosewhere, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 430));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Firma A", "Otobüs 1", "12", "300", "40"},
                {"Firma A", "Otobüs 2", "27", "300", "30"},
                {"Firma D", "Tren 1", "36", "250", "50"},
                {"Firma F", "Uçak 1", "22", "1000", "60"},
                {"Firma F", "Uçak 2", "56", "1000", "60"},
                {null, null, "30", "320", "45"},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Company", "Vehicle", "Fullness", "Price", "Capacity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(neredennereye, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Aramabutonpanelke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(neredennereye, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Aramabutonpanelke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed
    public String getTextField3value() {
        return jTextField3.getText(); 
    }
    public String getTextField2Value() {
        return jTextField2.getText();
    }
    private double totalPrice;

    private double calculateTotalPrice(int numberOfTickets) {
    TripInformation tripInfo = checkTripCapacity();
        
        if (tripInfo != null) {
            double pricePerTicket = tripInfo.getPricePerTicket();
            
            return pricePerTicket * numberOfTickets;
        }
        return 0.0; 
    }
    

    public double getTotalPrice1() {
        return totalPrice;
    }
    
    
    
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        
    TripInformation tripInfo = checkTripCapacity();

    if (tripInfo != null) {
        int selectedRowIndex = jTable1.getSelectedRow();
int numberOfTickets = tripInfo.getNumberOfTickets();

int dolulukColumnIndex = 2;

Object existingValueObject = jTable1.getValueAt(selectedRowIndex, dolulukColumnIndex);

if (existingValueObject != null) {
    int existingValue = Integer.parseInt(existingValueObject.toString());

    int newValue = existingValue + numberOfTickets;

    jTable1.setValueAt(newValue, selectedRowIndex, dolulukColumnIndex);
}

        payment odemeac = new payment();
        odemeac.setTripInformation(tripInfo); 
        odemeac.show(true);
    } else {
        JOptionPane.showMessageDialog(null, "Üzgünüz, yolculuk dolu veya istenilen sayıda bilet için yeterli yer yok.", "Bilet Onayı Başarısız!", JOptionPane.WARNING_MESSAGE);
    }
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void aramabutonuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aramabutonuMouseClicked
        // Tıklandığında seçili öğelere uygun seferler listemesi gerek
    DefaultTableModel jTable1Model = (DefaultTableModel) jTable1.getModel();
    jTable1Model.setRowCount(0);

    String from = From_Dropbox.getSelectedItem().toString();
    String to = To_Dropbox1.getSelectedItem().toString();
    
    HashMap<String, Trip> tripList = testinghanif.TripList;
    HashMap<String, Company> firms = testinghanif.firms;

    for (Company company : firms.values()) {
        for (Trip trip : tripList.values()) {
            double totalCost = 0.0;
            int totalCapacity = 0;

            for (Route route : trip.route) {
                if (route.getDeparture().equals(from) && route.getDestination().equals(to)
                        && route.getFirm().equals(company)) {
                    totalCost += route.getPrice();
                    totalCapacity += route.getCapacity();  // Use getCapacity() to get the capacity information
                }
            }
            // Create an instance of Route
                //Route routeInstance = new Route(from, to, Route.getVehiclesList(), Route.getDistance());

                // Now you can call non-static methods on routeInstance
                //Vehicle vehicle = routeInstance.getVehicle();
            if (totalCost >= 0.0) {
                //String vehicleName = vehicle.getVehicleName();
                // Add a row to jTable1 with the company, vehicle name, doluluk, totalCost, and totalCapacity
jTable1Model.addRow(new Object[]{
    company.getUserName(),
    from,  // Replace with the actual method to get the vehicle name
    to,  // This is placeholder text, you might want to replace it with the actual doluluk information
    totalCost,
    totalCapacity
});            }
        }
    }
    List<Trip> availableTrips = new ArrayList<>();
    List<Company> availableFirms = new ArrayList<>();
    }//GEN-LAST:event_aramabutonuMouseClicked

    
    private void aramabutonu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aramabutonu1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_aramabutonu1MouseClicked
    public class TripInformation {
    private int doluluk; // 3. sutun 
    private double pricePerTicket; // 4. sutun
    private int kapasite; // 5. sutun
    private int numberOfTickets;

    public TripInformation(int doluluk, int kapasite, double pricePerTicket, int numberOfTickets) {
        this.doluluk = doluluk;
        this.kapasite = kapasite;
        this.pricePerTicket = pricePerTicket;
        this.numberOfTickets = numberOfTickets;
    }

    public int getDoluluk() {
        return doluluk;
    }
    public int getNumberOfTickets() {
            return numberOfTickets;
        }
    public int getKapasite() {
        return kapasite;
    }

    public double getPricePerTicket() {
        return pricePerTicket;
    }

    public double getTotalPrice(int numberOfTickets) {
        return pricePerTicket * numberOfTickets;
    }
}
public class TripInformation1 {
    DefaultTableModel jTable1Model = (DefaultTableModel) jTable1.getModel();
    int selectedRowIndex = jTable1.getSelectedRow();

    private int doluluk = (int) jTable1Model.getValueAt(selectedRowIndex, 2); // Third column
    private double price = (double) jTable1Model.getValueAt(selectedRowIndex, 3); // Fourth column
    private int kapasite = (int) jTable1Model.getValueAt(selectedRowIndex, 4); // Fifth column
    int numberOfTicketsToBuy = Integer.parseInt(jTextField4.getText());

    public TripInformation1(int doluluk, double price, int kapasite) {
        this.doluluk = doluluk;
        this.price = price;
        this.kapasite = kapasite;
    }

    public int getDoluluk() {
        return doluluk;
    }

    public void setDoluluk(int doluluk) {
        this.doluluk = doluluk;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public int getKapasite() {
        return kapasite;
    }

    public void setKapasite(int kapasite) {
        this.kapasite = kapasite;
    }

    public double calculateTotalPrice() {
        return price * numberOfTicketsToBuy;
    }   
    }
private TripInformation checkTripCapacity() {
    DefaultTableModel jTable1Model = (DefaultTableModel) jTable1.getModel();
    int selectedRow = jTable1.getSelectedRow();

    if (selectedRow != -1) {
        // Doluluk
        Object valueColumn3 = jTable1.getValueAt(selectedRow, 2);
        // Kapasite
        Object valueColumn5 = jTable1.getValueAt(selectedRow, 4);

        int numberOfTicketsToBuy = 0;
        try {
            numberOfTicketsToBuy = Integer.parseInt(jTextField4.getText());
        } catch (NumberFormatException e) {
            
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Girdiğiniz değer bir sayı değil!", "Bilet Onayı Başarısız!", JOptionPane.WARNING_MESSAGE);

            return null; 
        }

        if (valueColumn3 != null && valueColumn5 != null) {
            int doluluk = Integer.parseInt(valueColumn3.toString());
            int kapasite = Integer.parseInt(valueColumn5.toString());
            int numberOfTickets = Integer.parseInt(jTextField4.getText());

            if (doluluk + numberOfTicketsToBuy > kapasite) {
                // Sefer dolu
                JOptionPane.showMessageDialog(null, "Seçtiğiniz sefer dolu. " + numberOfTicketsToBuy + " adet bilet için yer yok.", "Bilet Onayı Başarısız!", JOptionPane.WARNING_MESSAGE);
                return null;
            } else {
                // Seferde yer var
            return new TripInformation(doluluk, kapasite, Double.parseDouble(jTextField3.getText()), numberOfTickets);
            }
        }
        return null;
    }

    return null;
}
              

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // tabloda seçili satırdaki şirket ismini checkin kısmında göster
        DefaultTableModel jTable1Model = (DefaultTableModel) jTable1.getModel();
        int selectedRow = jTable1.getSelectedRow();
    
    if (selectedRow != -1) {
        // 1. sutun
        Object valueColumn1 = jTable1.getValueAt(selectedRow, 0);
        if (valueColumn1 == null || valueColumn1.toString().isEmpty()) {
            jTextField1.setText("N/A");
        } else {
            String firmName = valueColumn1.toString();
            jTextField1.setText(firmName);
        }

        // 2. sutun
        Object valueColumn2 = jTable1.getValueAt(selectedRow, 1);
        if (valueColumn2 == null || valueColumn2.toString().isEmpty()) {
            jTextField2.setText("N/A");
        } else {
            String value2 = valueColumn2.toString();
            jTextField2.setText(value2);
        }
        
        // 4. sutun
        Object valueColumn4 = jTable1.getValueAt(selectedRow, 3);
        if (valueColumn4 == null || valueColumn4.toString().isEmpty()) {
            jTextField3.setText("N/A");
        } else {
            String value4 = valueColumn4.toString();
            jTextField3.setText(value4);
        }
    }
    }//GEN-LAST:event_jTable1MouseClicked

    private void To_DropboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_To_DropboxActionPerformed
        
    }//GEN-LAST:event_To_DropboxActionPerformed
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new musteri1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Aramabutonpanel1;
    private javax.swing.JPanel Aramabutonpanelke;
    private javax.swing.JLabel Chosewhere;
    private javax.swing.JLabel Chosewhere1;
    private javax.swing.JLabel Departure;
    private javax.swing.JLabel From;
    private javax.swing.JComboBox<String> From_Dropbox;
    private javax.swing.JLabel To;
    private javax.swing.JComboBox<String> To_Dropbox;
    private javax.swing.JComboBox<String> To_Dropbox1;
    public javax.swing.JLabel aramabutonu;
    private javax.swing.JLabel aramabutonu1;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JPanel neredennereye;
    // End of variables declaration//GEN-END:variables
}
